name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Validation job for all events
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate JSON structure
        run: |
          echo "🔍 Validating JSON syntax..."
          python3 -m json.tool lngal_data.json > /dev/null
          echo "✅ JSON syntax is valid"

          echo "🔍 Checking required fields..."
          # Basic validation that categories exist
          if ! grep -q '"categories"' lngal_data.json; then
            echo "❌ Missing 'categories' field in JSON"
            exit 1
          fi

          # Check that there's at least one category
          category_count=$(python3 -c "import json; data=json.load(open('lngal_data.json')); print(len(data.get('categories', [])))")
          if [ "$category_count" -eq 0 ]; then
            echo "❌ No categories found in JSON"
            exit 1
          fi

          echo "✅ Found $category_count categories"
          echo "✅ JSON structure validation passed"

      - name: Validate project links
        run: |
          echo "🔍 Validating project links format..."
          python3 -c "
          import json
          import sys

          with open('lngal_data.json', 'r') as f:
              data = json.load(f)

          errors = []
          total_links = 0

          for category in data.get('categories', []):
              for item in category.get('items', []):
                  project_name = item.get('project_name', 'Unknown')
                  links = item.get('links', [])

                  for i, link in enumerate(links):
                      total_links += 1
                      # Check if link is an object
                      if not isinstance(link, dict):
                          errors.append(f'❌ {project_name}: Link {i+1} is not an object')
                          continue
                      # Check required fields
                      if 'type' not in link:
                          errors.append(f'❌ {project_name}: Link {i+1} missing \"type\" field')
                      elif not isinstance(link['type'], str) or not link['type'].strip():
                          errors.append(f'❌ {project_name}: Link {i+1} \"type\" field is empty or not a string')

                      if 'url' not in link:
                          errors.append(f'❌ {project_name}: Link {i+1} missing \"url\" field')
                      elif not isinstance(link['url'], str) or not link['url'].strip():
                          errors.append(f'❌ {project_name}: Link {i+1} \"url\" field is empty or not a string')
                      else:
                          url = link['url'].strip()
                          # Basic URL format validation
                          if not (url.startswith('http://') or url.startswith('https://')):
                              errors.append(f'❌ {project_name}: Link {i+1} URL must start with http:// or https://')

          if errors:
              print(f'Found {len(errors)} link validation errors:')
              for error in errors:
                  print(error)
              sys.exit(1)
          else:
              print(f'✅ All {total_links} project links are properly formatted')
          "
          echo "✅ Project links validation passed"

      - name: Test HTML validity
        run: |
          echo "🔍 Checking HTML structure..."
          # Basic HTML validation
          if ! grep -q '<html' index.html; then
            echo "❌ Invalid HTML structure"
            exit 1
          fi

          if ! grep -q '</html>' index.html; then
            echo "❌ HTML not properly closed"
            exit 1
          fi

          echo "✅ HTML structure is valid"

      - name: Check required files
        run: |
          echo "🔍 Checking required files exist..."
          required_files=("index.html" "styles.css" "js/app.js" "js/components.js" "lngal_data.json")

          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Required file missing: $file"
              exit 1
            fi
            echo "✅ Found: $file"
          done

          echo "✅ All required files present"

  # Deployment job only for pushes to main
  deploy:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare deployment files
        run: |
          echo "📦 Preparing files for deployment..."
          # Remove files that shouldn't be deployed
          rm -rf .github
          rm -f plan.md
          rm -f .gitignore

          # Ensure all required files are present
          ls -la
          echo "✅ Files prepared for deployment"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Deployment summary
        run: |
          echo "🚀 Deployment completed successfully!"
          echo "📊 Site URL: ${{ steps.deployment.outputs.page_url }}"
          echo "⏱️ Changes may take a few minutes to appear"
